name: cogenv

channels:
  - conda-forge

dependencies:
  - python=3.9
  - ipykernel
  - jupyter
  - notebook
  - flake8
  - pip:
    - -r requirements.txt
    # - git+https://github.com/deepmind/android_env/
    # - tensorflow==2.8.0
    # - dm-acme
    # - dm-acme[jax,tensrflow]
    # - dm-acme[envs]
    # - pandas
