name: cogenv

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - ipykernel
  - flake8
  - pytest
  - pip:
    - pandas
    - dm-env
    # - git+https://github.com/deepmind/dm_env.git
    # dm-acme[jax,tf,envs]
    - git+https://github.com/deepmind/acme.git#egg=dm-acme[jax,tf,envs]
    # android-env
    - git+https://github.com/deepmind/android_env/
