FROM mcr.microsoft.com/devcontainers/miniconda:3

# To add conda packages to the image uncomment the following commands,
# otherwise devcontainer.json will initialize the environment (see postCreateCommand)
# RUN /opt/conda/bin/conda update conda -n base
# RUN /opt/conda/bin/conda env create -f environment.yml

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
